
ValueSet: ClaimsStatusVS
Title:        "Claims status"
Description:  "Claims status"
* ^experimental = false
* ^name = "KNHTSCLMVS"

* KNHTS.CLMSTS#STS01
* KNHTS.CLMSTS#STS02
* KNHTS.CLMSTS#STS03
* KNHTS.CLMSTS#STS04
* KNHTS.CLMSTS#STS05
* KNHTS.CLMSTS#STS06
* KNHTS.CLMSTS#STS07
* KNHTS.CLMSTS#STS08
* KNHTS.CLMSTS#STS09
* KNHTS.CLMSTS#STS10
* KNHTS.CLMSTS#STS11
* KNHTS.CLMSTS#STS12


